server:
  port: 9999
  tomcat:
    max-threads: 1
    max-connections: 100


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.55.231.4:3306/im?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 1
    timeout: 3000
    host: 106.55.231.4
    port: 6379
    jedis:
      pool:
        # 连接池中的最大连接数
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 10
        min-idle: 0
        max-wait: -1
    password: 

im:
  port: 7000
  listener: im-listener01

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL

logging:
  level:
    com.junlin: debug